name: frontend-infra-ci
run-name: ${{ github.actor }} is testing out 🚀

on:
  push:
    branches: [main, master, develop]
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x, 22.x]
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
          node-version: ${{ matrix.node }}
  dependencies:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Starting dependencies
        run: yarn install
  build:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Build app
        run: yarn run build
  linters:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Run linters
        run: yarn run linters
  tests:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Test common js loader
        run: yarn run test:cjs
      - name: Test es modules loader
        run: yarn run test:esm
      - name: Test yaml
        run: yarn run test:yaml
  deploy:
    runs-on: ubuntu-latest
    needs: [dependencies, build]
    steps:
      - name: Run deploy
        run: yarn run deploy